apiVersion: apps/v1
kind: Deployment
metadata:
  name: jq-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jq-ctr
  template:
    metadata:
      labels:
        app: jq-ctr
    spec:
      serviceAccount: jq-adm
      containers:
      - image: portainer/kubectl-shell
        name: ctr
        volumeMounts:
        - name: scripts
          mountPath: /c
        - name: filter
          mountPath: /in
        command:
        - bash
        - /c/controller.sh
        env:
        - name: TRANSFORM_DEF_FILE
          value: /in/adm-jset.jq
        - name: WATCH_TARGET
          value: nodes
        - name: WATCH_MASK
          value: "."
      volumes:
      - name: scripts
        configMap:
          name: jq-controller
      - name: filter
        configMap:
          name: jq-filter
