apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jq-ctr
  name: jq-controller-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      jq-ctr: operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        jq-ctr: operator
    spec:
      containers:
        - command:
            - bash
            - /c/controller.sh
          env:
            - name: TRANSFORM_DEF_FILE
              value: /in/filter.jq
            - name: WATCH_TARGET
              value: jqcontrollers.xxx.jq
            - name: WATCH_MASK
              value: .
          image: portainer/kubectl-shell
          imagePullPolicy: Always
          name: ctr
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /c
              name: scripts
            - mountPath: /in
              name: filter
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jq-adm
      serviceAccountName: jq-adm
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: jq-controller
          name: scripts
        - configMap:
            defaultMode: 420
            name: jq-controller-operator.jq
          name: filter
