apiVersion: jq-ctr.io/v1alpha1
kind: JqController
metadata:
  name: node-tainter
  namespace: jq-ctr
spec:
  transform:
    filter: |-
      if hasTaint("unreachable") then
        .spec.taints |= (
          . + [
            {
              key: "node.kubernetes.io/out-of-service",
              effect: "NoSchedule"
            },
            {
              key: "node.kubernetes.io/out-of-service",
              effect: "NoExecute"
            }
          ]
          | unique_by(.key,.effect)
        )
      elif hasTaints then
        .spec.taints |= ([
          .[]
          | select(.key != "node.kubernetes.io/out-of-service")
        ])
        | .status.conditions += [{
          status: "Unknown",
          type: "Ready",
          message: "Removed out-of-service taint"
        }]
      else
        .
      end
    input:
      watchEvents: ADDED, MODIFIED
      watchMask: .spec.taints
      watchTarget:
        apiGroup: ""
        kind: nodes
    output:
      affectedObjectTypes:
        - apiGroup: ""
          kind: nodes
  watcherConfig:
    image: bitnami/kubectl
