apiVersion: jq-ctr.io/v1alpha1
kind: JqController
metadata:
  name: adm-ctr
  namespace: jq-ctr
spec:
  transform:
    filter: |-
      $source.metadata.name as $node
      ####### POD #####
      | pod( "adm-" + $node )
        | .spec |= (
          .
          | .nodeName = $node
          | .containers = [{
              name: "adm",
              image: "portainer/kubectl-shell",
              imagePullPolicy: "IfNotPresent",
              command: [ "tail", "-f", "/dev/null" ],
              securityContext: {
                capabilities: {"add": ["SYS_ADMIN"]},
                runAsUser: 0,
                privileged: true
              },
              volumeMounts: [{ name: "h", mountPath: "/h" }]
          }]
          | .volumes += [{
            name: "h",
            hostPath: { path: "/" }
          }]
          | .hostPID = true
          | .hostIPC = true
          | .securityContext = { fsGroup: 0 }
        )
        # END pod
      #| rs -- wrap it in a ReplicaSet
    input:
      watchEvents: ADDED, MODIFIED
      watchMask: .
      watchTarget:
        apiGroup: ""
        kind: nodes
    output:
      affectedObjectTypes:
        - apiGroup: ""
          kind: pods
    variablesFrom:
      - jqCtrLabel: cr-uid
        var: customResourceUid
  watcherConfig:
    image: bitnami/kubectl
