apiVersion: jq-ctr.io/v1alpha1
kind: JqController
metadata:
  name: adm-ctr
  namespace: jq-ctr
spec:
  transform:
    filter: |-
      include "lib";
      ## main
      .
      | . as $source
      | $source.metadata.name as $node
      | $source.metadata.uid as $uid
      ####### POD #####
      | deploy(
        pod( "adm-" + $node )
        ##
        | .metadata |= (
          .
          | .namespace = "jq-ctr"
          | .labels = {
            "jq-ctr.io/cr-name": $customResourceName,
            "jq-ctr.io/cr-uid": $customResourceUid,
            "jq-ctr.io/source-kind": $source.kind,
            "jq-ctr.io/source-name": $source.metadata.name,
            "jq-ctr.io/source-uid": $source.metadata.uid
          }
        )
        ##
        | .spec |= (
          .
          | .nodeName = $node
          | .serviceAccount = "jq-adm"
          | .containers = [{
              name: "adm",
              image: "portainer/kubectl-shell",
              imagePullPolicy: "IfNotPresent",
              command: [ "tail", "-f", "/dev/null" ],
              securityContext: {
                capabilities: {"add": ["NET_ADMIN"]}
              }
          }]
        )
        # END pod
      ) # END deployment
      ##
      | chown( "jq-ctr.io/v1alpha1"; "JqController";
               $customResourceName; $customResourceUid )
    input:
      watchEvents: ADDED, MODIFIED
      watchMask: .
      watchTarget:
        apiGroup: ""
        kind: nodes
    output:
      affectedObjectTypes:
        - apiGroup: apps
          kind: deployments
    variablesFrom:
      - jqCtrLabel: cr-uid
        var: customResourceUid
      - jqCtrLabel: cr-name
        var: customResourceName
  watcherConfig:
    image: bitnami/kubectl
