apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jqcontrollers.xxx.jq
spec:
  scope: Namespaced
  conversion:
    strategy: None
  group: xxx.jq
  names:
    kind: JqController
    listKind: JqControllerList
    plural: jqcontrollers
    shortNames:
      - jctr
      - jc
    singular: jqcontroller
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            spec:
              type: object
              properties:
                transform:
                  type: object
                  properties:
                    filter:
                      type: string
                    input:
                      type: object
                      properties:
                        watchEvents:
                          type: string
                        watchMask:
                          type: string
                        watchTarget:
                          type: object
                          properties:
                            apiGroup:
                              type: string
                            kind:
                              type: string
                            namespace:
                              type: string
                    output:
                      type: object
                      properties:
                        affectedObjectTypes:
                          type: array
                          items:
                            type: object
                            properties:
                              apiGroup:
                                type: string
                              kind:
                                type: string
                    variablesFrom:
                      type: array
                      items:
                        type: object
                        properties:
                          configMap:
                            type: string
                          field:
                            type: string
                          jqCtrLabel:
                            type: string
                          var:
                            type: string
                watcherConfig:
                  type: object
                  properties:
                    image:
                      type: string
